// Line-based highlighting for the report.
//
// The markdown markers (`###`, `- `) are kept and dimmed rather than stripped,
// because this pane is a preview of something you are about to paste
// elsewhere. Rendering it as prose would quietly misrepresent what lands in
// the clipboard.
//
// Deliberately not a markdown parser: the report's shape is generated by
// ccmon itself and is known line by line, so a pattern match is both
// sufficient and impossible to get subtly wrong on someone's commit subject.

export interface Piece {
  text: string;
  code: boolean;
}

export interface Line {
  cls: string;
  /** Leading markdown marker, rendered faintly. */
  marker: string;
  pieces: Piece[];
}

const TOTALS = /^\d+ projects? · /;

function classify(line: string): { cls: string; marker: string; rest: string } {
  if (line.startsWith("### ")) return { cls: "l-session", marker: "### ", rest: line.slice(4) };
  if (line.startsWith("## ")) return { cls: "l-project", marker: "## ", rest: line.slice(3) };
  if (line.startsWith("# ")) return { cls: "l-h1", marker: "# ", rest: line.slice(2) };
  if (line.startsWith("- ")) return { cls: "l-commit", marker: "- ", rest: line.slice(2) };
  if (line.startsWith("asked:")) return { cls: "l-ask", marker: "", rest: line };
  if (line.startsWith("files:") || line.startsWith("tickets:"))
    return { cls: "l-meta", marker: "", rest: line };
  if (line.startsWith("no commits")) return { cls: "l-none", marker: "", rest: line };
  if (TOTALS.test(line)) return { cls: "l-total", marker: "", rest: line };
  return { cls: "", marker: "", rest: line };
}

/** Split on backticks so inline code can be coloured without any HTML. */
function pieces(text: string): Piece[] {
  return text
    .split("`")
    .map((part, i) => ({ text: part, code: i % 2 === 1 }))
    .filter((p) => p.text.length > 0);
}

export function highlight(markdown: string): Line[] {
  return markdown.split("\n").map((raw) => {
    const { cls, marker, rest } = classify(raw);
    return { cls, marker, pieces: pieces(rest) };
  });
}
